export interface Database {
  public: {
    Tables: {
      teachers: {
        Row: {
          id: string;
          email: string;
          name: string;
          phone: string | null;
          subject: string | null;
          hourly_rate: number;
          address: string | null;
          working_hours_start: string;
          working_hours_end: string;
          working_days: string[];
          bio: string | null;
          avatar: string | null;
          specializations: string[];
          experience: number;
          qualifications: string[];
          role: 'teacher' | 'admin' | 'supervisor';
          is_active: boolean;
          join_date: string;
          last_login: string | null;
          rating: number;
          total_students: number;
          total_groups: number;
          total_sessions: number;
          total_revenue: number;
          preferences: any;
          social_links: any;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          email: string;
          name: string;
          phone?: string | null;
          subject?: string | null;
          hourly_rate?: number;
          address?: string | null;
          working_hours_start?: string;
          working_hours_end?: string;
          working_days?: string[];
          bio?: string | null;
          avatar?: string | null;
          specializations?: string[];
          experience?: number;
          qualifications?: string[];
          role?: 'teacher' | 'admin' | 'supervisor';
          is_active?: boolean;
          join_date?: string;
          last_login?: string | null;
          rating?: number;
          total_students?: number;
          total_groups?: number;
          total_sessions?: number;
          total_revenue?: number;
          preferences?: any;
          social_links?: any;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          name?: string;
          phone?: string | null;
          subject?: string | null;
          hourly_rate?: number;
          address?: string | null;
          working_hours_start?: string;
          working_hours_end?: string;
          working_days?: string[];
          bio?: string | null;
          avatar?: string | null;
          specializations?: string[];
          experience?: number;
          qualifications?: string[];
          role?: 'teacher' | 'admin' | 'supervisor';
          is_active?: boolean;
          join_date?: string;
          last_login?: string | null;
          rating?: number;
          total_students?: number;
          total_groups?: number;
          total_sessions?: number;
          total_revenue?: number;
          preferences?: any;
          social_links?: any;
          created_at?: string;
          updated_at?: string;
        };
      };
      teacher_permissions: {
        Row: {
          id: string;
          teacher_id: string;
          permission_name: string;
          permission_category: 'students' | 'groups' | 'sessions' | 'payments' | 'reports' | 'settings' | 'admin';
          description: string | null;
          is_granted: boolean;
          granted_by: string | null;
          granted_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          teacher_id: string;
          permission_name: string;
          permission_category: 'students' | 'groups' | 'sessions' | 'payments' | 'reports' | 'settings' | 'admin';
          description?: string | null;
          is_granted?: boolean;
          granted_by?: string | null;
          granted_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          teacher_id?: string;
          permission_name?: string;
          permission_category?: 'students' | 'groups' | 'sessions' | 'payments' | 'reports' | 'settings' | 'admin';
          description?: string | null;
          is_granted?: boolean;
          granted_by?: string | null;
          granted_at?: string | null;
          created_at?: string;
        };
      };
      teacher_documents: {
        Row: {
          id: string;
          teacher_id: string;
          name: string;
          type: 'cv' | 'certificate' | 'id' | 'photo' | 'other';
          url: string;
          upload_date: string;
          file_size: number | null;
          mime_type: string | null;
          is_verified: boolean;
          verified_by: string | null;
          verified_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          teacher_id: string;
          name: string;
          type: 'cv' | 'certificate' | 'id' | 'photo' | 'other';
          url: string;
          upload_date?: string;
          file_size?: number | null;
          mime_type?: string | null;
          is_verified?: boolean;
          verified_by?: string | null;
          verified_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          teacher_id?: string;
          name?: string;
          type?: 'cv' | 'certificate' | 'id' | 'photo' | 'other';
          url?: string;
          upload_date?: string;
          file_size?: number | null;
          mime_type?: string | null;
          is_verified?: boolean;
          verified_by?: string | null;
          verified_at?: string | null;
          created_at?: string;
        };
      };
      teacher_subjects: {
        Row: {
          id: string;
          teacher_id: string;
          subject_id: string;
          is_primary: boolean;
          hourly_rate: number | null;
          experience_years: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          teacher_id: string;
          subject_id: string;
          is_primary?: boolean;
          hourly_rate?: number | null;
          experience_years?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          teacher_id?: string;
          subject_id?: string;
          is_primary?: boolean;
          hourly_rate?: number | null;
          experience_years?: number;
          created_at?: string;
        };
      };
      teacher_stats: {
        Row: {
          id: string;
          teacher_id: string;
          stat_date: string;
          students_count: number;
          groups_count: number;
          sessions_count: number;
          revenue_amount: number;
          attendance_rate: number;
          payment_rate: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          teacher_id: string;
          stat_date?: string;
          students_count?: number;
          groups_count?: number;
          sessions_count?: number;
          revenue_amount?: number;
          attendance_rate?: number;
          payment_rate?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          teacher_id?: string;
          stat_date?: string;
          students_count?: number;
          groups_count?: number;
          sessions_count?: number;
          revenue_amount?: number;
          attendance_rate?: number;
          payment_rate?: number;
          created_at?: string;
        };
      };
      subjects: {
        Row: {
          id: string;
          teacher_id: string;
          name: string;
          code: string;
          category: 'علوم' | 'أدب' | 'لغات' | 'رياضيات' | 'اجتماعيات' | 'فنون' | 'أخرى';
          color: string;
          icon: string;
          description: string | null;
          grades: string[];
          default_duration: number;
          default_price: number;
          materials: string[];
          objectives: string[];
          prerequisites: string[];
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          teacher_id: string;
          name: string;
          code: string;
          category?: 'علوم' | 'أدب' | 'لغات' | 'رياضيات' | 'اجتماعيات' | 'فنون' | 'أخرى';
          color?: string;
          icon?: string;
          description?: string | null;
          grades?: string[];
          default_duration?: number;
          default_price?: number;
          materials?: string[];
          objectives?: string[];
          prerequisites?: string[];
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          teacher_id?: string;
          name?: string;
          code?: string;
          category?: 'علوم' | 'أدب' | 'لغات' | 'رياضيات' | 'اجتماعيات' | 'فنون' | 'أخرى';
          color?: string;
          icon?: string;
          description?: string | null;
          grades?: string[];
          default_duration?: number;
          default_price?: number;
          materials?: string[];
          objectives?: string[];
          prerequisites?: string[];
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      student_groups: {
        Row: {
          id: string;
          teacher_id: string;
          subject_id: string;
          name: string;
          grade: string;
          description: string | null;
          monthly_price: number;
          max_students: number;
          current_students: number;
          location: string | null;
          materials: string[];
          rules: string[];
          start_date: string | null;
          end_date: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          teacher_id: string;
          subject_id: string;
          name: string;
          grade: string;
          description?: string | null;
          monthly_price?: number;
          max_students?: number;
          current_students?: number;
          location?: string | null;
          materials?: string[];
          rules?: string[];
          start_date?: string | null;
          end_date?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          teacher_id?: string;
          subject_id?: string;
          name?: string;
          grade?: string;
          description?: string | null;
          monthly_price?: number;
          max_students?: number;
          current_students?: number;
          location?: string | null;
          materials?: string[];
          rules?: string[];
          start_date?: string | null;
          end_date?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      group_schedules: {
        Row: {
          id: string;
          group_id: string;
          day: 'السبت' | 'الأحد' | 'الاثنين' | 'الثلاثاء' | 'الأربعاء' | 'الخميس' | 'الجمعة';
          start_time: string;
          end_time: string;
          duration: number;
          location: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          group_id: string;
          day: 'السبت' | 'الأحد' | 'الاثنين' | 'الثلاثاء' | 'الأربعاء' | 'الخميس' | 'الجمعة';
          start_time: string;
          end_time: string;
          duration?: number;
          location?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          group_id?: string;
          day?: 'السبت' | 'الأحد' | 'الاثنين' | 'الثلاثاء' | 'الأربعاء' | 'الخميس' | 'الجمعة';
          start_time?: string;
          end_time?: string;
          duration?: number;
          location?: string | null;
          created_at?: string;
        };
      };
      group_students: {
        Row: {
          id: string;
          group_id: string;
          student_id: string;
          joined_at: string;
          is_active: boolean;
        };
        Insert: {
          id?: string;
          group_id: string;
          student_id: string;
          joined_at?: string;
          is_active?: boolean;
        };
        Update: {
          id?: string;
          group_id?: string;
          student_id?: string;
          joined_at?: string;
          is_active?: boolean;
        };
      };
      students: {
        Row: {
          id: string;
          teacher_id: string;
          name: string;
          phone: string;
          parent_phone: string | null;
          grade: string;
          subject: string;
          subject_id: string | null;
          student_code: string | null;
          address: string | null;
          notes: string | null;
          is_active: boolean;
          avatar: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          teacher_id: string;
          name: string;
          phone: string;
          parent_phone?: string | null;
          grade: string;
          subject: string;
          subject_id?: string | null;
          student_code?: string | null;
          address?: string | null;
          notes?: string | null;
          is_active?: boolean;
          avatar?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          teacher_id?: string;
          name?: string;
          phone?: string;
          parent_phone?: string | null;
          grade?: string;
          subject?: string;
          subject_id?: string | null;
          student_code?: string | null;
          address?: string | null;
          notes?: string | null;
          is_active?: boolean;
          avatar?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      sessions: {
        Row: {
          id: string;
          teacher_id: string;
          student_id: string;
          subject_id: string | null;
          group_id: string | null;
          date: string;
          duration: number;
          topic: string;
          homework: string | null;
          notes: string | null;
          payment: number;
          is_paid: boolean;
          status: 'scheduled' | 'completed' | 'cancelled' | 'missed';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          teacher_id: string;
          student_id: string;
          subject_id?: string | null;
          group_id?: string | null;
          date: string;
          duration?: number;
          topic: string;
          homework?: string | null;
          notes?: string | null;
          payment?: number;
          is_paid?: boolean;
          status?: 'scheduled' | 'completed' | 'cancelled' | 'missed';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          teacher_id?: string;
          student_id?: string;
          subject_id?: string | null;
          group_id?: string | null;
          date?: string;
          duration?: number;
          topic?: string;
          homework?: string | null;
          notes?: string | null;
          payment?: number;
          is_paid?: boolean;
          status?: 'scheduled' | 'completed' | 'cancelled' | 'missed';
          created_at?: string;
          updated_at?: string;
        };
      };
      payments: {
        Row: {
          id: string;
          teacher_id: string;
          student_id: string;
          session_id: string | null;
          subject_id: string | null;
          group_id: string | null;
          amount: number;
          date: string;
          type: 'session' | 'monthly' | 'package';
          notes: string | null;
          method: 'cash' | 'transfer' | 'other';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          teacher_id: string;
          student_id: string;
          session_id?: string | null;
          subject_id?: string | null;
          group_id?: string | null;
          amount: number;
          date?: string;
          type?: 'session' | 'monthly' | 'package';
          notes?: string | null;
          method?: 'cash' | 'transfer' | 'other';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          teacher_id?: string;
          student_id?: string;
          session_id?: string | null;
          subject_id?: string | null;
          group_id?: string | null;
          amount?: number;
          date?: string;
          type?: 'session' | 'monthly' | 'package';
          notes?: string | null;
          method?: 'cash' | 'transfer' | 'other';
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {
      teacher_dashboard_stats: {
        Row: {
          id: string;
          name: string;
          email: string;
          total_students: number;
          total_groups: number;
          total_sessions: number;
          total_revenue: number;
          rating: number;
          is_active: boolean;
          students_this_month: number;
          sessions_this_month: number;
          revenue_this_month: number;
          sessions_today: number;
          revenue_today: number;
          completion_rate: number;
          payment_rate: number;
        };
      };
    };
    Functions: {
      calculate_teacher_stats: {
        Args: { teacher_uuid: string };
        Returns: void;
      };
    };
    Enums: {
      [_ in never]: never;
    };
  };
}